export const portfolioGridData = [
  {
    title: "House",
    subTitle: "Full repaint in white",
    outerFilter: "residential",
    innerFilter: "exterior",
    imgBefore: "house_before.jpeg",
    imgAfter: "house_after.jpeg",
  },
  {
    title: "Coffe Shop",
    subTitle: "Modern colors painting",
    outerFilter: "commercial",
    innerFilter: "exterior",
    imgBefore: "coffeshop_before.jpg",
    imgAfter: "coffeshop_after.jpg",
  },
  {
    title: "Warehouse",
    subTitle: "Safe from wet and damp",
    outerFilter: "commercial",
    innerFilter: "exterior",
    imgBefore: "commercial_before.jpg",
    imgAfter: "commercial_after.jpg",
  },
  {
    title: "Kitchen",
    subTitle: "Sleek and functional design",
    outerFilter: "residential",
    innerFilter: "interior",
    imgBefore: "kitchen_before.jpeg",
    imgAfter: "kitchen_after.jpeg",
  },
  {
    title: "Office Makeover",
    subTitle: "From traditional to modern workspace",
    outerFilter: "commercial",
    innerFilter: "interior",
    imgBefore: "office_before.jpg",
    imgAfter: "office_after.jpg",
  },
  {
    title: "Residential House",
    subTitle: "New modern and clean look",
    outerFilter: "residential",
    innerFilter: "exterior",
    imgBefore: "mansion_before.jpeg",
    imgAfter: "mansion_after.jpeg",
  },
  {
    title: "Residential vila",
    subTitle: "Inviting and modern front",
    outerFilter: "residential",
    innerFilter: "exterior",
    imgBefore: "residentialhouse-before.jpeg",
    imgAfter: "residentialhouse-after.jpeg",
  },
  {
    title: "Grey & White",
    subTitle: "Elegant look",
    outerFilter: "residential",
    innerFilter: "exterior",
    imgBefore: "vila_before.jpeg",
    imgAfter: "vila_after.jpeg",
  },
  {
    title: "Garage",
    subTitle: "Profesional redesign",
    outerFilter: "commercial",
    innerFilter: "exterior",
    imgBefore: "warehouse_before.jpg",
    imgAfter: "warehouse_after.jpg",
  },
];
